name: CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: Target Environment
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    uses: winddevops-org/devops-templates/.github/workflows/deploy.yml@main
    with:
      environment: ${{ github.event.inputs.environment || 'staging' }}
    secrets:
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
